<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/survey/survey.proto

namespace Ondewo\Survey\Survey;

use UnexpectedValueException;

/**
 * Protobuf type <code>ondewo.survey.Survey.AgentStatus</code>
 */
class AgentStatus
{
    /**
     * Generated from protobuf enum <code>TO_BE_INITIALIZED = 0;</code>
     */
    const TO_BE_INITIALIZED = 0;
    /**
     * Generated from protobuf enum <code>UPDATED = 1;</code>
     */
    const UPDATED = 1;
    /**
     * Generated from protobuf enum <code>UPDATING = 2;</code>
     */
    const UPDATING = 2;
    /**
     * Generated from protobuf enum <code>OUTDATED = 3;</code>
     */
    const OUTDATED = 3;

    private static $valueToName = [
        self::TO_BE_INITIALIZED => 'TO_BE_INITIALIZED',
        self::UPDATED => 'UPDATED',
        self::UPDATING => 'UPDATING',
        self::OUTDATED => 'OUTDATED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

