<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/survey/fhir.proto

namespace GPBMetadata\Ondewo\Survey;

class Fhir
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Ondewo\Survey\Survey::initOnce();
        \GPBMetadata\Google\Protobuf\Struct::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xE2\x05\x0A\x18ondewo/survey/fhir.proto\x12\x0Dondewo.survey\x1A\x1Aondewo/survey/survey.proto\x1A\x1Cgoogle/protobuf/struct.proto\"N\x0A\x17CreateFHIRSurveyRequest\x123\x0A\x12fhir_questionnaire\x18\x01 \x01(\x0B2\x17.google.protobuf.Struct\"m\x0A\x19SurveyFHIRAnswersResponse\x12\x11\x0A\x09survey_id\x18\x01 \x01(\x09\x12=\x0A\x1Cfhir_questionnaire_responses\x18\x02 \x03(\x0B2\x17.google.protobuf.Struct2\xB5\x03\x0A\x04FHIR\x12j\x0A\x10CreateFHIRSurvey\x12&.ondewo.survey.CreateFHIRSurveyRequest\x1A\x15.ondewo.survey.Survey\"\x17\x82\xD3\xE4\x93\x02\x11\"\x0C/fhir_survey:\x01*\x12\xA3\x01\x0A\x14GetFHIRSurveyAnswers\x12&.ondewo.survey.GetSurveyAnswersRequest\x1A(.ondewo.survey.SurveyFHIRAnswersResponse\"9\x82\xD3\xE4\x93\x023\x121/survey/{survey_id=*}/fhir_answers/{session_id=*}\x12\x9A\x01\x0A\x17GetAllFHIRSurveyAnswers\x12).ondewo.survey.GetAllSurveyAnswersRequest\x1A(.ondewo.survey.SurveyFHIRAnswersResponse\"*\x82\xD3\xE4\x93\x02\$\x12\"/survey/{survey_id=*}/fhir_answersb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

