<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/survey/survey.proto

namespace Ondewo\Survey\Answer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>ondewo.survey.Answer.UserInfo</code>
 */
class UserInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * First name of the User to be surveyed
     *
     * Generated from protobuf field <code>string first_name = 1;</code>
     */
    protected $first_name = '';
    /**
     * Last name of the User to be surveyed
     *
     * Generated from protobuf field <code>string last_name = 2;</code>
     */
    protected $last_name = '';
    /**
     * Phone number of the User to be surveyed
     *
     * Generated from protobuf field <code>string phone_number = 3;</code>
     */
    protected $phone_number = '';
    /**
     * the ID of the session on which the answer was collected
     *
     * Generated from protobuf field <code>string session_id = 4;</code>
     */
    protected $session_id = '';
    /**
     * Unique identifier of the User to be surveyed
     *
     * Generated from protobuf field <code>string user_id = 5;</code>
     */
    protected $user_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $first_name
     *           First name of the User to be surveyed
     *     @type string $last_name
     *           Last name of the User to be surveyed
     *     @type string $phone_number
     *           Phone number of the User to be surveyed
     *     @type string $session_id
     *           the ID of the session on which the answer was collected
     *     @type string $user_id
     *           Unique identifier of the User to be surveyed
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Survey\Survey::initOnce();
        parent::__construct($data);
    }

    /**
     * First name of the User to be surveyed
     *
     * Generated from protobuf field <code>string first_name = 1;</code>
     * @return string
     */
    public function getFirstName()
    {
        return $this->first_name;
    }

    /**
     * First name of the User to be surveyed
     *
     * Generated from protobuf field <code>string first_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFirstName($var)
    {
        GPBUtil::checkString($var, True);
        $this->first_name = $var;

        return $this;
    }

    /**
     * Last name of the User to be surveyed
     *
     * Generated from protobuf field <code>string last_name = 2;</code>
     * @return string
     */
    public function getLastName()
    {
        return $this->last_name;
    }

    /**
     * Last name of the User to be surveyed
     *
     * Generated from protobuf field <code>string last_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLastName($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_name = $var;

        return $this;
    }

    /**
     * Phone number of the User to be surveyed
     *
     * Generated from protobuf field <code>string phone_number = 3;</code>
     * @return string
     */
    public function getPhoneNumber()
    {
        return $this->phone_number;
    }

    /**
     * Phone number of the User to be surveyed
     *
     * Generated from protobuf field <code>string phone_number = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPhoneNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone_number = $var;

        return $this;
    }

    /**
     * the ID of the session on which the answer was collected
     *
     * Generated from protobuf field <code>string session_id = 4;</code>
     * @return string
     */
    public function getSessionId()
    {
        return $this->session_id;
    }

    /**
     * the ID of the session on which the answer was collected
     *
     * Generated from protobuf field <code>string session_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->session_id = $var;

        return $this;
    }

    /**
     * Unique identifier of the User to be surveyed
     *
     * Generated from protobuf field <code>string user_id = 5;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Unique identifier of the User to be surveyed
     *
     * Generated from protobuf field <code>string user_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

}

