<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/survey/survey.proto

namespace Ondewo\Survey;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>ondewo.survey.Answer</code>
 */
class Answer extends \Google\Protobuf\Internal\Message
{
    /**
     * the number of the question to which this answer belongs
     *
     * Generated from protobuf field <code>int64 question_nr = 1;</code>
     */
    protected $question_nr = 0;
    /**
     * the ID of the session on which the answer was collected
     *
     * Generated from protobuf field <code>string session_id = 2;</code>
     */
    protected $session_id = '';
    /**
     * Required; the full answer text
     *
     * Generated from protobuf field <code>string answer_text = 3;</code>
     */
    protected $answer_text = '';
    /**
     * fixme: better names and doc-strings below
     * Optional; contains the normalized value of the selected option (parameter) extracted
     *
     * Generated from protobuf field <code>string answer_parameter = 4;</code>
     */
    protected $answer_parameter = '';
    /**
     * Optional; contains the original text of the selected option (parameter) extracted
     *
     * Generated from protobuf field <code>string answer_parameter_original = 5;</code>
     */
    protected $answer_parameter_original = '';
    protected $is_anonymous;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $question_nr
     *           the number of the question to which this answer belongs
     *     @type string $session_id
     *           the ID of the session on which the answer was collected
     *     @type string $answer_text
     *           Required; the full answer text
     *     @type string $answer_parameter
     *           fixme: better names and doc-strings below
     *           Optional; contains the normalized value of the selected option (parameter) extracted
     *     @type string $answer_parameter_original
     *           Optional; contains the original text of the selected option (parameter) extracted
     *     @type bool $anonymous
     *     @type \Ondewo\Survey\Answer\UserInfo $user_information
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Survey\Survey::initOnce();
        parent::__construct($data);
    }

    /**
     * the number of the question to which this answer belongs
     *
     * Generated from protobuf field <code>int64 question_nr = 1;</code>
     * @return int|string
     */
    public function getQuestionNr()
    {
        return $this->question_nr;
    }

    /**
     * the number of the question to which this answer belongs
     *
     * Generated from protobuf field <code>int64 question_nr = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setQuestionNr($var)
    {
        GPBUtil::checkInt64($var);
        $this->question_nr = $var;

        return $this;
    }

    /**
     * the ID of the session on which the answer was collected
     *
     * Generated from protobuf field <code>string session_id = 2;</code>
     * @return string
     */
    public function getSessionId()
    {
        return $this->session_id;
    }

    /**
     * the ID of the session on which the answer was collected
     *
     * Generated from protobuf field <code>string session_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->session_id = $var;

        return $this;
    }

    /**
     * Required; the full answer text
     *
     * Generated from protobuf field <code>string answer_text = 3;</code>
     * @return string
     */
    public function getAnswerText()
    {
        return $this->answer_text;
    }

    /**
     * Required; the full answer text
     *
     * Generated from protobuf field <code>string answer_text = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAnswerText($var)
    {
        GPBUtil::checkString($var, True);
        $this->answer_text = $var;

        return $this;
    }

    /**
     * fixme: better names and doc-strings below
     * Optional; contains the normalized value of the selected option (parameter) extracted
     *
     * Generated from protobuf field <code>string answer_parameter = 4;</code>
     * @return string
     */
    public function getAnswerParameter()
    {
        return $this->answer_parameter;
    }

    /**
     * fixme: better names and doc-strings below
     * Optional; contains the normalized value of the selected option (parameter) extracted
     *
     * Generated from protobuf field <code>string answer_parameter = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAnswerParameter($var)
    {
        GPBUtil::checkString($var, True);
        $this->answer_parameter = $var;

        return $this;
    }

    /**
     * Optional; contains the original text of the selected option (parameter) extracted
     *
     * Generated from protobuf field <code>string answer_parameter_original = 5;</code>
     * @return string
     */
    public function getAnswerParameterOriginal()
    {
        return $this->answer_parameter_original;
    }

    /**
     * Optional; contains the original text of the selected option (parameter) extracted
     *
     * Generated from protobuf field <code>string answer_parameter_original = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setAnswerParameterOriginal($var)
    {
        GPBUtil::checkString($var, True);
        $this->answer_parameter_original = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool anonymous = 7;</code>
     * @return bool
     */
    public function getAnonymous()
    {
        return $this->readOneof(7);
    }

    public function hasAnonymous()
    {
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>bool anonymous = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setAnonymous($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ondewo.survey.Answer.UserInfo user_information = 6;</code>
     * @return \Ondewo\Survey\Answer\UserInfo|null
     */
    public function getUserInformation()
    {
        return $this->readOneof(6);
    }

    public function hasUserInformation()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.ondewo.survey.Answer.UserInfo user_information = 6;</code>
     * @param \Ondewo\Survey\Answer\UserInfo $var
     * @return $this
     */
    public function setUserInformation($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Survey\Answer\UserInfo::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getIsAnonymous()
    {
        return $this->whichOneof("is_anonymous");
    }

}

