<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/survey/survey.proto

namespace Ondewo\Survey;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The Choice message defines one "option" for the SingleChoiceQuestion and MultipleChoiceQuestion question types
 * Example: Choice(synonyms=["blue", "blueish", "pale blue", "deep blue"])
 *
 * Generated from protobuf message <code>ondewo.survey.Choice</code>
 */
class Choice extends \Google\Protobuf\Internal\Message
{
    /**
     * The synonyms which are recognized as equivalent for identifying one option
     *
     * Generated from protobuf field <code>repeated string synonyms = 1;</code>
     */
    private $synonyms;
    /**
     * Optional; Nested question if this specific choice gets chosen.
     * Note: the follow-up question is only available for the SingleChoiceQuestion
     *
     * Generated from protobuf field <code>.ondewo.survey.Question follow_up_question = 2;</code>
     */
    protected $follow_up_question = null;
    /**
     * The "canonical value" (i.e. the entity value)
     *
     * Generated from protobuf field <code>string value = 3;</code>
     */
    protected $value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $synonyms
     *           The synonyms which are recognized as equivalent for identifying one option
     *     @type \Ondewo\Survey\Question $follow_up_question
     *           Optional; Nested question if this specific choice gets chosen.
     *           Note: the follow-up question is only available for the SingleChoiceQuestion
     *     @type string $value
     *           The "canonical value" (i.e. the entity value)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Survey\Survey::initOnce();
        parent::__construct($data);
    }

    /**
     * The synonyms which are recognized as equivalent for identifying one option
     *
     * Generated from protobuf field <code>repeated string synonyms = 1;</code>
     * @return RepeatedField<string>
     */
    public function getSynonyms()
    {
        return $this->synonyms;
    }

    /**
     * The synonyms which are recognized as equivalent for identifying one option
     *
     * Generated from protobuf field <code>repeated string synonyms = 1;</code>
     * @param string[] $var
     * @return $this
     */
    public function setSynonyms($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->synonyms = $arr;

        return $this;
    }

    /**
     * Optional; Nested question if this specific choice gets chosen.
     * Note: the follow-up question is only available for the SingleChoiceQuestion
     *
     * Generated from protobuf field <code>.ondewo.survey.Question follow_up_question = 2;</code>
     * @return \Ondewo\Survey\Question|null
     */
    public function getFollowUpQuestion()
    {
        return $this->follow_up_question;
    }

    public function hasFollowUpQuestion()
    {
        return isset($this->follow_up_question);
    }

    public function clearFollowUpQuestion()
    {
        unset($this->follow_up_question);
    }

    /**
     * Optional; Nested question if this specific choice gets chosen.
     * Note: the follow-up question is only available for the SingleChoiceQuestion
     *
     * Generated from protobuf field <code>.ondewo.survey.Question follow_up_question = 2;</code>
     * @param \Ondewo\Survey\Question $var
     * @return $this
     */
    public function setFollowUpQuestion($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Survey\Question::class);
        $this->follow_up_question = $var;

        return $this;
    }

    /**
     * The "canonical value" (i.e. the entity value)
     *
     * Generated from protobuf field <code>string value = 3;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * The "canonical value" (i.e. the entity value)
     *
     * Generated from protobuf field <code>string value = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

}

