<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/survey/fhir.proto

namespace Ondewo\Survey;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>ondewo.survey.CreateFHIRSurveyRequest</code>
 */
class CreateFHIRSurveyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * FHIR questionnaire on a gRPC Struct format
     *
     * Generated from protobuf field <code>.google.protobuf.Struct fhir_questionnaire = 1;</code>
     */
    protected $fhir_questionnaire = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Struct $fhir_questionnaire
     *           FHIR questionnaire on a gRPC Struct format
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Survey\Fhir::initOnce();
        parent::__construct($data);
    }

    /**
     * FHIR questionnaire on a gRPC Struct format
     *
     * Generated from protobuf field <code>.google.protobuf.Struct fhir_questionnaire = 1;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getFhirQuestionnaire()
    {
        return $this->fhir_questionnaire;
    }

    public function hasFhirQuestionnaire()
    {
        return isset($this->fhir_questionnaire);
    }

    public function clearFhirQuestionnaire()
    {
        unset($this->fhir_questionnaire);
    }

    /**
     * FHIR questionnaire on a gRPC Struct format
     *
     * Generated from protobuf field <code>.google.protobuf.Struct fhir_questionnaire = 1;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setFhirQuestionnaire($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->fhir_questionnaire = $var;

        return $this;
    }

}

