<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/survey/survey.proto

namespace Ondewo\Survey;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Request message for creating a new survey
 *
 * Generated from protobuf message <code>ondewo.survey.CreateSurveyRequest</code>
 */
class CreateSurveyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The survey to create
     *
     * Generated from protobuf field <code>.ondewo.survey.Survey survey = 1;</code>
     */
    protected $survey = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ondewo\Survey\Survey $survey
     *           The survey to create
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Survey\Survey::initOnce();
        parent::__construct($data);
    }

    /**
     * The survey to create
     *
     * Generated from protobuf field <code>.ondewo.survey.Survey survey = 1;</code>
     * @return \Ondewo\Survey\Survey|null
     */
    public function getSurvey()
    {
        return $this->survey;
    }

    public function hasSurvey()
    {
        return isset($this->survey);
    }

    public function clearSurvey()
    {
        unset($this->survey);
    }

    /**
     * The survey to create
     *
     * Generated from protobuf field <code>.ondewo.survey.Survey survey = 1;</code>
     * @param \Ondewo\Survey\Survey $var
     * @return $this
     */
    public function setSurvey($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Survey\Survey::class);
        $this->survey = $var;

        return $this;
    }

}

