<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/survey/survey.proto

namespace Ondewo\Survey;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>ondewo.survey.GetSurveyAnswersRequest</code>
 */
class GetSurveyAnswersRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string survey_id = 1;</code>
     */
    protected $survey_id = '';
    protected $identifier;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $survey_id
     *     @type string $session_id
     *           ID of one specific session on which survey answers were collected (contains survey_id)
     *     @type string $user_id
     *           User Identifier. Note, if the survey is anonymous there will no identifier to filter on
     *     @type string $user_phone_number
     *           User phone number. Note, if the survey is anonymous there will no identifier to filter on
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Survey\Survey::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string survey_id = 1;</code>
     * @return string
     */
    public function getSurveyId()
    {
        return $this->survey_id;
    }

    /**
     * Generated from protobuf field <code>string survey_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSurveyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->survey_id = $var;

        return $this;
    }

    /**
     * ID of one specific session on which survey answers were collected (contains survey_id)
     *
     * Generated from protobuf field <code>string session_id = 2;</code>
     * @return string
     */
    public function getSessionId()
    {
        return $this->readOneof(2);
    }

    public function hasSessionId()
    {
        return $this->hasOneof(2);
    }

    /**
     * ID of one specific session on which survey answers were collected (contains survey_id)
     *
     * Generated from protobuf field <code>string session_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * User Identifier. Note, if the survey is anonymous there will no identifier to filter on
     *
     * Generated from protobuf field <code>string user_id = 3;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->readOneof(3);
    }

    public function hasUserId()
    {
        return $this->hasOneof(3);
    }

    /**
     * User Identifier. Note, if the survey is anonymous there will no identifier to filter on
     *
     * Generated from protobuf field <code>string user_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * User phone number. Note, if the survey is anonymous there will no identifier to filter on
     *
     * Generated from protobuf field <code>string user_phone_number = 4;</code>
     * @return string
     */
    public function getUserPhoneNumber()
    {
        return $this->readOneof(4);
    }

    public function hasUserPhoneNumber()
    {
        return $this->hasOneof(4);
    }

    /**
     * User phone number. Note, if the survey is anonymous there will no identifier to filter on
     *
     * Generated from protobuf field <code>string user_phone_number = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUserPhoneNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getIdentifier()
    {
        return $this->whichOneof("identifier");
    }

}

