<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/survey/survey.proto

namespace Ondewo\Survey;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>ondewo.survey.GetSurveyRequest</code>
 */
class GetSurveyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The project identifier for this survey. Equal to the parent of the corresponding Agent.
     * Format: `projects/<Project ID>/agent`.
     *
     * Generated from protobuf field <code>string survey_id = 1;</code>
     */
    protected $survey_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $survey_id
     *           The project identifier for this survey. Equal to the parent of the corresponding Agent.
     *           Format: `projects/<Project ID>/agent`.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Survey\Survey::initOnce();
        parent::__construct($data);
    }

    /**
     * The project identifier for this survey. Equal to the parent of the corresponding Agent.
     * Format: `projects/<Project ID>/agent`.
     *
     * Generated from protobuf field <code>string survey_id = 1;</code>
     * @return string
     */
    public function getSurveyId()
    {
        return $this->survey_id;
    }

    /**
     * The project identifier for this survey. Equal to the parent of the corresponding Agent.
     * Format: `projects/<Project ID>/agent`.
     *
     * Generated from protobuf field <code>string survey_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSurveyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->survey_id = $var;

        return $this;
    }

}

