<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/survey/survey.proto

namespace Ondewo\Survey;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>ondewo.survey.ListSurveysRequest</code>
 */
class ListSurveysRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Optional. The next_page_token value returned from a previous list request.
     * Example:
     *      "current_index-10--page_size-20"
     *      Start page -> 10
     *      Page size -> 20
     *
     * Generated from protobuf field <code>string page_token = 1;</code>
     */
    protected $page_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $page_token
     *           Optional. The next_page_token value returned from a previous list request.
     *           Example:
     *                "current_index-10--page_size-20"
     *                Start page -> 10
     *                Page size -> 20
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Survey\Survey::initOnce();
        parent::__construct($data);
    }

    /**
     * Optional. The next_page_token value returned from a previous list request.
     * Example:
     *      "current_index-10--page_size-20"
     *      Start page -> 10
     *      Page size -> 20
     *
     * Generated from protobuf field <code>string page_token = 1;</code>
     * @return string
     */
    public function getPageToken()
    {
        return $this->page_token;
    }

    /**
     * Optional. The next_page_token value returned from a previous list request.
     * Example:
     *      "current_index-10--page_size-20"
     *      Start page -> 10
     *      Page size -> 20
     *
     * Generated from protobuf field <code>string page_token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->page_token = $var;

        return $this;
    }

}

