<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/survey/survey.proto

namespace Ondewo\Survey;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The response message for [Intents.ListIntents][google.cloud.dialogflow.v2.Intents.ListIntents].
 *
 * Generated from protobuf message <code>ondewo.survey.ListSurveysResponse</code>
 */
class ListSurveysResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The list of surveys. There will be a maximum number of items
     * returned based on the page_token field in the request.
     *
     * Generated from protobuf field <code>repeated .ondewo.survey.Survey surveys = 1;</code>
     */
    private $surveys;
    /**
     * Token to retrieve the next page of results, or empty if there are no
     * more results in the list.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     */
    protected $next_page_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ondewo\Survey\Survey[] $surveys
     *           The list of surveys. There will be a maximum number of items
     *           returned based on the page_token field in the request.
     *     @type string $next_page_token
     *           Token to retrieve the next page of results, or empty if there are no
     *           more results in the list.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Survey\Survey::initOnce();
        parent::__construct($data);
    }

    /**
     * The list of surveys. There will be a maximum number of items
     * returned based on the page_token field in the request.
     *
     * Generated from protobuf field <code>repeated .ondewo.survey.Survey surveys = 1;</code>
     * @return RepeatedField<\Ondewo\Survey\Survey>
     */
    public function getSurveys()
    {
        return $this->surveys;
    }

    /**
     * The list of surveys. There will be a maximum number of items
     * returned based on the page_token field in the request.
     *
     * Generated from protobuf field <code>repeated .ondewo.survey.Survey surveys = 1;</code>
     * @param \Ondewo\Survey\Survey[] $var
     * @return $this
     */
    public function setSurveys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ondewo\Survey\Survey::class);
        $this->surveys = $arr;

        return $this;
    }

    /**
     * Token to retrieve the next page of results, or empty if there are no
     * more results in the list.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @return string
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * Token to retrieve the next page of results, or empty if there are no
     * more results in the list.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_page_token = $var;

        return $this;
    }

}

