<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/survey/survey.proto

namespace Ondewo\Survey;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * MultipleParameterQuestion defines a question which prompts the user for one or several entities of one particular type
 * Example: MultipleParameterQuestion(question_text='How old are your children?', parameter_type='sys.number')
 *
 * Generated from protobuf message <code>ondewo.survey.MultipleParameterQuestion</code>
 */
class MultipleParameterQuestion extends \Google\Protobuf\Internal\Message
{
    /**
     * The text which introduces the question (should be pronounceable)
     *
     * Generated from protobuf field <code>string question_text = 1;</code>
     */
    protected $question_text = '';
    /**
     * The display name of the entity (type) which is accepted as an answer to this question
     * Note: the corresponding entity_type must exist (system entity type) and is not automatically created
     *
     * Generated from protobuf field <code>string parameter_type = 2;</code>
     */
    protected $parameter_type = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $question_text
     *           The text which introduces the question (should be pronounceable)
     *     @type string $parameter_type
     *           The display name of the entity (type) which is accepted as an answer to this question
     *           Note: the corresponding entity_type must exist (system entity type) and is not automatically created
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Survey\Survey::initOnce();
        parent::__construct($data);
    }

    /**
     * The text which introduces the question (should be pronounceable)
     *
     * Generated from protobuf field <code>string question_text = 1;</code>
     * @return string
     */
    public function getQuestionText()
    {
        return $this->question_text;
    }

    /**
     * The text which introduces the question (should be pronounceable)
     *
     * Generated from protobuf field <code>string question_text = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setQuestionText($var)
    {
        GPBUtil::checkString($var, True);
        $this->question_text = $var;

        return $this;
    }

    /**
     * The display name of the entity (type) which is accepted as an answer to this question
     * Note: the corresponding entity_type must exist (system entity type) and is not automatically created
     *
     * Generated from protobuf field <code>string parameter_type = 2;</code>
     * @return string
     */
    public function getParameterType()
    {
        return $this->parameter_type;
    }

    /**
     * The display name of the entity (type) which is accepted as an answer to this question
     * Note: the corresponding entity_type must exist (system entity type) and is not automatically created
     *
     * Generated from protobuf field <code>string parameter_type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setParameterType($var)
    {
        GPBUtil::checkString($var, True);
        $this->parameter_type = $var;

        return $this;
    }

}

