<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/survey/survey.proto

namespace Ondewo\Survey;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A question to which any kind of reply can be given and recorded
 * fixme: not working yet
 *
 * Generated from protobuf message <code>ondewo.survey.OpenQuestion</code>
 */
class OpenQuestion extends \Google\Protobuf\Internal\Message
{
    /**
     * The text which introduces the question (should be pronounceable)
     *
     * Generated from protobuf field <code>string question_text = 1;</code>
     */
    protected $question_text = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $question_text
     *           The text which introduces the question (should be pronounceable)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Survey\Survey::initOnce();
        parent::__construct($data);
    }

    /**
     * The text which introduces the question (should be pronounceable)
     *
     * Generated from protobuf field <code>string question_text = 1;</code>
     * @return string
     */
    public function getQuestionText()
    {
        return $this->question_text;
    }

    /**
     * The text which introduces the question (should be pronounceable)
     *
     * Generated from protobuf field <code>string question_text = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setQuestionText($var)
    {
        GPBUtil::checkString($var, True);
        $this->question_text = $var;

        return $this;
    }

}

