<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/survey/survey.proto

namespace Ondewo\Survey;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>ondewo.survey.Question</code>
 */
class Question extends \Google\Protobuf\Internal\Message
{
    protected $question;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ondewo\Survey\OpenQuestion $open_question
     *     @type \Ondewo\Survey\SingleChoiceQuestion $single_choice_question
     *     @type \Ondewo\Survey\MultipleChoiceQuestion $multiple_choice_question
     *     @type \Ondewo\Survey\ScaleQuestion $scale_question
     *           convenience wrapper around a SingleChoiceQuestion
     *     @type \Ondewo\Survey\SingleParameterQuestion $single_parameter_question
     *     @type \Ondewo\Survey\MultipleParameterQuestion $multiple_parameter_question
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Survey\Survey::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ondewo.survey.OpenQuestion open_question = 1;</code>
     * @return \Ondewo\Survey\OpenQuestion|null
     */
    public function getOpenQuestion()
    {
        return $this->readOneof(1);
    }

    public function hasOpenQuestion()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.ondewo.survey.OpenQuestion open_question = 1;</code>
     * @param \Ondewo\Survey\OpenQuestion $var
     * @return $this
     */
    public function setOpenQuestion($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Survey\OpenQuestion::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ondewo.survey.SingleChoiceQuestion single_choice_question = 2;</code>
     * @return \Ondewo\Survey\SingleChoiceQuestion|null
     */
    public function getSingleChoiceQuestion()
    {
        return $this->readOneof(2);
    }

    public function hasSingleChoiceQuestion()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.ondewo.survey.SingleChoiceQuestion single_choice_question = 2;</code>
     * @param \Ondewo\Survey\SingleChoiceQuestion $var
     * @return $this
     */
    public function setSingleChoiceQuestion($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Survey\SingleChoiceQuestion::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ondewo.survey.MultipleChoiceQuestion multiple_choice_question = 3;</code>
     * @return \Ondewo\Survey\MultipleChoiceQuestion|null
     */
    public function getMultipleChoiceQuestion()
    {
        return $this->readOneof(3);
    }

    public function hasMultipleChoiceQuestion()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.ondewo.survey.MultipleChoiceQuestion multiple_choice_question = 3;</code>
     * @param \Ondewo\Survey\MultipleChoiceQuestion $var
     * @return $this
     */
    public function setMultipleChoiceQuestion($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Survey\MultipleChoiceQuestion::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * convenience wrapper around a SingleChoiceQuestion
     *
     * Generated from protobuf field <code>.ondewo.survey.ScaleQuestion scale_question = 4;</code>
     * @return \Ondewo\Survey\ScaleQuestion|null
     */
    public function getScaleQuestion()
    {
        return $this->readOneof(4);
    }

    public function hasScaleQuestion()
    {
        return $this->hasOneof(4);
    }

    /**
     * convenience wrapper around a SingleChoiceQuestion
     *
     * Generated from protobuf field <code>.ondewo.survey.ScaleQuestion scale_question = 4;</code>
     * @param \Ondewo\Survey\ScaleQuestion $var
     * @return $this
     */
    public function setScaleQuestion($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Survey\ScaleQuestion::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ondewo.survey.SingleParameterQuestion single_parameter_question = 5;</code>
     * @return \Ondewo\Survey\SingleParameterQuestion|null
     */
    public function getSingleParameterQuestion()
    {
        return $this->readOneof(5);
    }

    public function hasSingleParameterQuestion()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.ondewo.survey.SingleParameterQuestion single_parameter_question = 5;</code>
     * @param \Ondewo\Survey\SingleParameterQuestion $var
     * @return $this
     */
    public function setSingleParameterQuestion($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Survey\SingleParameterQuestion::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ondewo.survey.MultipleParameterQuestion multiple_parameter_question = 6;</code>
     * @return \Ondewo\Survey\MultipleParameterQuestion|null
     */
    public function getMultipleParameterQuestion()
    {
        return $this->readOneof(6);
    }

    public function hasMultipleParameterQuestion()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.ondewo.survey.MultipleParameterQuestion multiple_parameter_question = 6;</code>
     * @param \Ondewo\Survey\MultipleParameterQuestion $var
     * @return $this
     */
    public function setMultipleParameterQuestion($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Survey\MultipleParameterQuestion::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getQuestion()
    {
        return $this->whichOneof("question");
    }

}

