<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/survey/survey.proto

namespace Ondewo\Survey;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A question for which an answer on a user-defined scale is expected
 *
 * Generated from protobuf message <code>ondewo.survey.ScaleQuestion</code>
 */
class ScaleQuestion extends \Google\Protobuf\Internal\Message
{
    /**
     * The text which introduces the question (should be pronounceable)
     *
     * Generated from protobuf field <code>string question_text = 1;</code>
     */
    protected $question_text = '';
    /**
     * Generated from protobuf field <code>.ondewo.survey.ScaleQuestion.ScaleValue min_value = 2;</code>
     */
    protected $min_value = null;
    /**
     * Generated from protobuf field <code>.ondewo.survey.ScaleQuestion.ScaleValue max_value = 3;</code>
     */
    protected $max_value = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $question_text
     *           The text which introduces the question (should be pronounceable)
     *     @type \Ondewo\Survey\ScaleQuestion\ScaleValue $min_value
     *     @type \Ondewo\Survey\ScaleQuestion\ScaleValue $max_value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Survey\Survey::initOnce();
        parent::__construct($data);
    }

    /**
     * The text which introduces the question (should be pronounceable)
     *
     * Generated from protobuf field <code>string question_text = 1;</code>
     * @return string
     */
    public function getQuestionText()
    {
        return $this->question_text;
    }

    /**
     * The text which introduces the question (should be pronounceable)
     *
     * Generated from protobuf field <code>string question_text = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setQuestionText($var)
    {
        GPBUtil::checkString($var, True);
        $this->question_text = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ondewo.survey.ScaleQuestion.ScaleValue min_value = 2;</code>
     * @return \Ondewo\Survey\ScaleQuestion\ScaleValue|null
     */
    public function getMinValue()
    {
        return $this->min_value;
    }

    public function hasMinValue()
    {
        return isset($this->min_value);
    }

    public function clearMinValue()
    {
        unset($this->min_value);
    }

    /**
     * Generated from protobuf field <code>.ondewo.survey.ScaleQuestion.ScaleValue min_value = 2;</code>
     * @param \Ondewo\Survey\ScaleQuestion\ScaleValue $var
     * @return $this
     */
    public function setMinValue($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Survey\ScaleQuestion\ScaleValue::class);
        $this->min_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ondewo.survey.ScaleQuestion.ScaleValue max_value = 3;</code>
     * @return \Ondewo\Survey\ScaleQuestion\ScaleValue|null
     */
    public function getMaxValue()
    {
        return $this->max_value;
    }

    public function hasMaxValue()
    {
        return isset($this->max_value);
    }

    public function clearMaxValue()
    {
        unset($this->max_value);
    }

    /**
     * Generated from protobuf field <code>.ondewo.survey.ScaleQuestion.ScaleValue max_value = 3;</code>
     * @param \Ondewo\Survey\ScaleQuestion\ScaleValue $var
     * @return $this
     */
    public function setMaxValue($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Survey\ScaleQuestion\ScaleValue::class);
        $this->max_value = $var;

        return $this;
    }

}

