<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/survey/survey.proto

namespace Ondewo\Survey;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A question for which exactly one out of a predefined set of options is expected as answer
 * Example: SingleChoiceQuestion(
 *      question_text='Who is your favorite movie hero?',
 *      choices=[
 *          Choice(synonyms=['Bond', 'James Bond']),
 *          Choice(synonyms=['Batman']),
 *          Choice(synonyms=['Superman', 'Clark Kent']),
 *          ]
 *      )
 *
 * Generated from protobuf message <code>ondewo.survey.SingleChoiceQuestion</code>
 */
class SingleChoiceQuestion extends \Google\Protobuf\Internal\Message
{
    /**
     * The text which introduces the question (should be pronounceable)
     *
     * Generated from protobuf field <code>string question_text = 1;</code>
     */
    protected $question_text = '';
    /**
     * List of choices which are accepted for this question
     * Each Choice is represented by lists of synonyms.
     * Note: needs to contain at least 2 choices
     *
     * Generated from protobuf field <code>repeated .ondewo.survey.Choice choices = 2;</code>
     */
    private $choices;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $question_text
     *           The text which introduces the question (should be pronounceable)
     *     @type \Ondewo\Survey\Choice[] $choices
     *           List of choices which are accepted for this question
     *           Each Choice is represented by lists of synonyms.
     *           Note: needs to contain at least 2 choices
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Survey\Survey::initOnce();
        parent::__construct($data);
    }

    /**
     * The text which introduces the question (should be pronounceable)
     *
     * Generated from protobuf field <code>string question_text = 1;</code>
     * @return string
     */
    public function getQuestionText()
    {
        return $this->question_text;
    }

    /**
     * The text which introduces the question (should be pronounceable)
     *
     * Generated from protobuf field <code>string question_text = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setQuestionText($var)
    {
        GPBUtil::checkString($var, True);
        $this->question_text = $var;

        return $this;
    }

    /**
     * List of choices which are accepted for this question
     * Each Choice is represented by lists of synonyms.
     * Note: needs to contain at least 2 choices
     *
     * Generated from protobuf field <code>repeated .ondewo.survey.Choice choices = 2;</code>
     * @return RepeatedField<\Ondewo\Survey\Choice>
     */
    public function getChoices()
    {
        return $this->choices;
    }

    /**
     * List of choices which are accepted for this question
     * Each Choice is represented by lists of synonyms.
     * Note: needs to contain at least 2 choices
     *
     * Generated from protobuf field <code>repeated .ondewo.survey.Choice choices = 2;</code>
     * @param \Ondewo\Survey\Choice[] $var
     * @return $this
     */
    public function setChoices($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ondewo\Survey\Choice::class);
        $this->choices = $arr;

        return $this;
    }

}

