<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/survey/survey.proto

namespace Ondewo\Survey;

use UnexpectedValueException;

/**
 * <p>Enumeration of (some of) the subflows which are created by default</p>
 * <p>This can be used to &quot;switch off&quot; particular subflows when creating an agent during CreateSurvey</p>
 * <p>Subflows are defined as one of the following:</p>
 * <ul>
 *   <li>sequences of intents A -&gt; B_1, ..., B_n -&gt; ... -&gt; Z_1, ..., Z_m which are linked by context relationships such that the first intent in the sequence can always be triggered</li>
 *   <li>single intents which can always be triggered</li>
 * </ul>
 *
 * Protobuf type <code>ondewo.survey.SubFlow</code>
 */
class SubFlow
{
    /**
     * Not specified. This value should be never used.
     *
     * Generated from protobuf enum <code>SUBFLOW_UNSPECIFIED = 0;</code>
     */
    const SUBFLOW_UNSPECIFIED = 0;
    /**
     * The subflow allowing the user to inquire whether s/he is talking to a bot
     *
     * Generated from protobuf enum <code>BOT = 1;</code>
     */
    const BOT = 1;
    /**
     * The subflow allowing the user to inquire about the legal entity
     *
     * Generated from protobuf enum <code>LEGAL_ENTITY = 2;</code>
     */
    const LEGAL_ENTITY = 2;
    /**
     * The subflow allowing the user to inquire about the postal address
     *
     * Generated from protobuf enum <code>POSTAL_ADDRESS = 3;</code>
     */
    const POSTAL_ADDRESS = 3;
    /**
     * The subflow allowing the user to inquire about the email address
     *
     * Generated from protobuf enum <code>EMAIL_ADDRESS = 4;</code>
     */
    const EMAIL_ADDRESS = 4;
    /**
     * The subflow allowing the user to inquire about the phone number
     *
     * Generated from protobuf enum <code>PHONE_NUMBER = 5;</code>
     */
    const PHONE_NUMBER = 5;
    /**
     * The subflow allowing the user to inquire about the phone hours
     *
     * Generated from protobuf enum <code>PHONE_HOURS = 6;</code>
     */
    const PHONE_HOURS = 6;
    /**
     * The subflow allowing the user to inquire about the expected duration of the survey
     *
     * Generated from protobuf enum <code>EXPECTED_DURATION = 7;</code>
     */
    const EXPECTED_DURATION = 7;
    /**
     * The subflow allowing the user to inquire about the purpose of the survey
     *
     * Generated from protobuf enum <code>PURPOSE = 8;</code>
     */
    const PURPOSE = 8;

    private static $valueToName = [
        self::SUBFLOW_UNSPECIFIED => 'SUBFLOW_UNSPECIFIED',
        self::BOT => 'BOT',
        self::LEGAL_ENTITY => 'LEGAL_ENTITY',
        self::POSTAL_ADDRESS => 'POSTAL_ADDRESS',
        self::EMAIL_ADDRESS => 'EMAIL_ADDRESS',
        self::PHONE_NUMBER => 'PHONE_NUMBER',
        self::PHONE_HOURS => 'PHONE_HOURS',
        self::EXPECTED_DURATION => 'EXPECTED_DURATION',
        self::PURPOSE => 'PURPOSE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

