<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/survey/fhir.proto

namespace Ondewo\Survey;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>ondewo.survey.SurveyFHIRAnswersResponse</code>
 */
class SurveyFHIRAnswersResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The project identifier for this survey. Equal to the parent of the corresponding Agent.
     * Format: `projects/<Project ID>/agent`.
     *
     * Generated from protobuf field <code>string survey_id = 1;</code>
     */
    protected $survey_id = '';
    /**
     * all requested answers
     *
     * Generated from protobuf field <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
     */
    private $fhir_questionnaire_responses;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $survey_id
     *           The project identifier for this survey. Equal to the parent of the corresponding Agent.
     *           Format: `projects/<Project ID>/agent`.
     *     @type \Google\Protobuf\Struct[] $fhir_questionnaire_responses
     *           all requested answers
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Survey\Fhir::initOnce();
        parent::__construct($data);
    }

    /**
     * The project identifier for this survey. Equal to the parent of the corresponding Agent.
     * Format: `projects/<Project ID>/agent`.
     *
     * Generated from protobuf field <code>string survey_id = 1;</code>
     * @return string
     */
    public function getSurveyId()
    {
        return $this->survey_id;
    }

    /**
     * The project identifier for this survey. Equal to the parent of the corresponding Agent.
     * Format: `projects/<Project ID>/agent`.
     *
     * Generated from protobuf field <code>string survey_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSurveyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->survey_id = $var;

        return $this;
    }

    /**
     * all requested answers
     *
     * Generated from protobuf field <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
     * @return RepeatedField<\Google\Protobuf\Struct>
     */
    public function getFhirQuestionnaireResponses()
    {
        return $this->fhir_questionnaire_responses;
    }

    /**
     * all requested answers
     *
     * Generated from protobuf field <code>repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;</code>
     * @param \Google\Protobuf\Struct[] $var
     * @return $this
     */
    public function setFhirQuestionnaireResponses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Struct::class);
        $this->fhir_questionnaire_responses = $arr;

        return $this;
    }

}

