<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/survey/survey.proto

namespace Ondewo\Survey;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>ondewo.survey.Survey</code>
 */
class Survey extends \Google\Protobuf\Internal\Message
{
    /**
     * The project identifier for this survey. Equal to the parent of the corresponding Agent.
     * Format: `projects/<Project ID>/agent`.
     * Read-only in the Survey message (assigned by the back-end)
     *
     * Generated from protobuf field <code>string survey_id = 1;</code>
     */
    protected $survey_id = '';
    /**
     * Required. The (human readable) name of this survey
     *
     * Generated from protobuf field <code>string display_name = 2;</code>
     */
    protected $display_name = '';
    /**
     * Required. The language of the agent created for the survey.
     * This is also the only supported language of the agent.
     *
     * Generated from protobuf field <code>string language_code = 3;</code>
     */
    protected $language_code = '';
    /**
     * Required. List of questions to be asked during the survey.
     *
     * Generated from protobuf field <code>repeated .ondewo.survey.Question questions = 7;</code>
     */
    private $questions;
    /**
     * Required. Information about the entity behind the survey, the purpose of the survey, legal stuff, etc.
     *
     * Generated from protobuf field <code>.ondewo.survey.SurveyInfo survey_info = 8;</code>
     */
    protected $survey_info = null;
    /**
     * Optional. List of subflows excluded for this survey.
     *
     * Generated from protobuf field <code>repeated .ondewo.survey.SubFlow exclude_subflows = 9;</code>
     */
    private $exclude_subflows;
    /**
     * Current status of the NLU Agent respecting to the Survey
     *
     * Generated from protobuf field <code>.ondewo.survey.Survey.AgentStatus status = 10;</code>
     */
    protected $status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $survey_id
     *           The project identifier for this survey. Equal to the parent of the corresponding Agent.
     *           Format: `projects/<Project ID>/agent`.
     *           Read-only in the Survey message (assigned by the back-end)
     *     @type string $display_name
     *           Required. The (human readable) name of this survey
     *     @type string $language_code
     *           Required. The language of the agent created for the survey.
     *           This is also the only supported language of the agent.
     *     @type \Ondewo\Survey\Question[] $questions
     *           Required. List of questions to be asked during the survey.
     *     @type \Ondewo\Survey\SurveyInfo $survey_info
     *           Required. Information about the entity behind the survey, the purpose of the survey, legal stuff, etc.
     *     @type int[] $exclude_subflows
     *           Optional. List of subflows excluded for this survey.
     *     @type int $status
     *           Current status of the NLU Agent respecting to the Survey
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Survey\Survey::initOnce();
        parent::__construct($data);
    }

    /**
     * The project identifier for this survey. Equal to the parent of the corresponding Agent.
     * Format: `projects/<Project ID>/agent`.
     * Read-only in the Survey message (assigned by the back-end)
     *
     * Generated from protobuf field <code>string survey_id = 1;</code>
     * @return string
     */
    public function getSurveyId()
    {
        return $this->survey_id;
    }

    /**
     * The project identifier for this survey. Equal to the parent of the corresponding Agent.
     * Format: `projects/<Project ID>/agent`.
     * Read-only in the Survey message (assigned by the back-end)
     *
     * Generated from protobuf field <code>string survey_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSurveyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->survey_id = $var;

        return $this;
    }

    /**
     * Required. The (human readable) name of this survey
     *
     * Generated from protobuf field <code>string display_name = 2;</code>
     * @return string
     */
    public function getDisplayName()
    {
        return $this->display_name;
    }

    /**
     * Required. The (human readable) name of this survey
     *
     * Generated from protobuf field <code>string display_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDisplayName($var)
    {
        GPBUtil::checkString($var, True);
        $this->display_name = $var;

        return $this;
    }

    /**
     * Required. The language of the agent created for the survey.
     * This is also the only supported language of the agent.
     *
     * Generated from protobuf field <code>string language_code = 3;</code>
     * @return string
     */
    public function getLanguageCode()
    {
        return $this->language_code;
    }

    /**
     * Required. The language of the agent created for the survey.
     * This is also the only supported language of the agent.
     *
     * Generated from protobuf field <code>string language_code = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLanguageCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->language_code = $var;

        return $this;
    }

    /**
     * Required. List of questions to be asked during the survey.
     *
     * Generated from protobuf field <code>repeated .ondewo.survey.Question questions = 7;</code>
     * @return RepeatedField<\Ondewo\Survey\Question>
     */
    public function getQuestions()
    {
        return $this->questions;
    }

    /**
     * Required. List of questions to be asked during the survey.
     *
     * Generated from protobuf field <code>repeated .ondewo.survey.Question questions = 7;</code>
     * @param \Ondewo\Survey\Question[] $var
     * @return $this
     */
    public function setQuestions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ondewo\Survey\Question::class);
        $this->questions = $arr;

        return $this;
    }

    /**
     * Required. Information about the entity behind the survey, the purpose of the survey, legal stuff, etc.
     *
     * Generated from protobuf field <code>.ondewo.survey.SurveyInfo survey_info = 8;</code>
     * @return \Ondewo\Survey\SurveyInfo|null
     */
    public function getSurveyInfo()
    {
        return $this->survey_info;
    }

    public function hasSurveyInfo()
    {
        return isset($this->survey_info);
    }

    public function clearSurveyInfo()
    {
        unset($this->survey_info);
    }

    /**
     * Required. Information about the entity behind the survey, the purpose of the survey, legal stuff, etc.
     *
     * Generated from protobuf field <code>.ondewo.survey.SurveyInfo survey_info = 8;</code>
     * @param \Ondewo\Survey\SurveyInfo $var
     * @return $this
     */
    public function setSurveyInfo($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Survey\SurveyInfo::class);
        $this->survey_info = $var;

        return $this;
    }

    /**
     * Optional. List of subflows excluded for this survey.
     *
     * Generated from protobuf field <code>repeated .ondewo.survey.SubFlow exclude_subflows = 9;</code>
     * @return RepeatedField<int>
     */
    public function getExcludeSubflows()
    {
        return $this->exclude_subflows;
    }

    /**
     * Optional. List of subflows excluded for this survey.
     *
     * Generated from protobuf field <code>repeated .ondewo.survey.SubFlow exclude_subflows = 9;</code>
     * @param int[] $var
     * @return $this
     */
    public function setExcludeSubflows($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Ondewo\Survey\SubFlow::class);
        $this->exclude_subflows = $arr;

        return $this;
    }

    /**
     * Current status of the NLU Agent respecting to the Survey
     *
     * Generated from protobuf field <code>.ondewo.survey.Survey.AgentStatus status = 10;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Current status of the NLU Agent respecting to the Survey
     *
     * Generated from protobuf field <code>.ondewo.survey.Survey.AgentStatus status = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Ondewo\Survey\Survey\AgentStatus::class);
        $this->status = $var;

        return $this;
    }

}

