<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/survey/survey.proto

namespace Ondewo\Survey;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Collect information about the entity behind the survey, the purpose of the survey, legal stuff, etc.
 * This is needed to generate meaningful messages and training data for some of the auto-generated intents.
 *
 * Generated from protobuf message <code>ondewo.survey.SurveyInfo</code>
 */
class SurveyInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Required unless SubFlow.LEGAL_ENTITY is deselected.
     * The legal entity (company, research institute, etc.) on whose behalf the survey is performed
     *
     * Generated from protobuf field <code>string legal_entity = 1;</code>
     */
    protected $legal_entity = '';
    /**
     * Required unless SubFlow.POSTAL_ADDRESS is deselected.
     * The postal address to which callees can direct any requests.
     *
     * Generated from protobuf field <code>string postal_address = 2;</code>
     */
    protected $postal_address = '';
    /**
     * Required unless SubFlow.EMAIL_ADDRESS is deselected.
     * The email address to which callees can direct any requests.
     *
     * Generated from protobuf field <code>string email_address = 3;</code>
     */
    protected $email_address = '';
    /**
     * Required unless SubFlow.PHONE_NUMBER is deselected.
     * The phone number to which callees can direct any requests.
     *
     * Generated from protobuf field <code>string phone_number = 4;</code>
     */
    protected $phone_number = '';
    /**
     * Required unless SubFlow.PHONE_HOURS is deselected.
     * The phone hours during which callees can call (in pronounceable form).
     *
     * Generated from protobuf field <code>string phone_hours = 5;</code>
     */
    protected $phone_hours = '';
    /**
     * Required unless SubFlow.EXPECTED_DURATION is deselected.
     * The expected duration of the survey (in pronounceable form)
     *
     * Generated from protobuf field <code>string expected_duration = 6;</code>
     */
    protected $expected_duration = '';
    /**
     * Required unless SubFlow.PURPOSE is deselected.
     * An explanation regarding the purpose of the survey (in pronounceable form)
     *
     * Generated from protobuf field <code>string purpose = 7;</code>
     */
    protected $purpose = '';
    /**
     * Required.
     * A one-word explanation of the survey topic (in pronounceable form)
     *
     * Generated from protobuf field <code>string topic = 8;</code>
     */
    protected $topic = '';
    /**
     * Required.
     * A pronounceable explanation of the legal implications of participating in the survey.
     * For example:
     *  "Your answers during this survey will be stored anonymously for the next two years and then deleted."
     * Should be formulated such that the agent can afterwards ask for the consent of the user.
     * Example for how the agent could continue: "Are you willing to participate in this survey?"
     *
     * Generated from protobuf field <code>string legal_disclaimer = 9;</code>
     */
    protected $legal_disclaimer = '';
    /**
     * Optional.
     * Defaults to False. Allows the definition of a survey as anonymous or not.
     * If the survey is not anonymous, the name of the people as well as their number will be recorded
     *
     * Generated from protobuf field <code>bool anonymous = 10;</code>
     */
    protected $anonymous = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $legal_entity
     *           Required unless SubFlow.LEGAL_ENTITY is deselected.
     *           The legal entity (company, research institute, etc.) on whose behalf the survey is performed
     *     @type string $postal_address
     *           Required unless SubFlow.POSTAL_ADDRESS is deselected.
     *           The postal address to which callees can direct any requests.
     *     @type string $email_address
     *           Required unless SubFlow.EMAIL_ADDRESS is deselected.
     *           The email address to which callees can direct any requests.
     *     @type string $phone_number
     *           Required unless SubFlow.PHONE_NUMBER is deselected.
     *           The phone number to which callees can direct any requests.
     *     @type string $phone_hours
     *           Required unless SubFlow.PHONE_HOURS is deselected.
     *           The phone hours during which callees can call (in pronounceable form).
     *     @type string $expected_duration
     *           Required unless SubFlow.EXPECTED_DURATION is deselected.
     *           The expected duration of the survey (in pronounceable form)
     *     @type string $purpose
     *           Required unless SubFlow.PURPOSE is deselected.
     *           An explanation regarding the purpose of the survey (in pronounceable form)
     *     @type string $topic
     *           Required.
     *           A one-word explanation of the survey topic (in pronounceable form)
     *     @type string $legal_disclaimer
     *           Required.
     *           A pronounceable explanation of the legal implications of participating in the survey.
     *           For example:
     *            "Your answers during this survey will be stored anonymously for the next two years and then deleted."
     *           Should be formulated such that the agent can afterwards ask for the consent of the user.
     *           Example for how the agent could continue: "Are you willing to participate in this survey?"
     *     @type bool $anonymous
     *           Optional.
     *           Defaults to False. Allows the definition of a survey as anonymous or not.
     *           If the survey is not anonymous, the name of the people as well as their number will be recorded
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Survey\Survey::initOnce();
        parent::__construct($data);
    }

    /**
     * Required unless SubFlow.LEGAL_ENTITY is deselected.
     * The legal entity (company, research institute, etc.) on whose behalf the survey is performed
     *
     * Generated from protobuf field <code>string legal_entity = 1;</code>
     * @return string
     */
    public function getLegalEntity()
    {
        return $this->legal_entity;
    }

    /**
     * Required unless SubFlow.LEGAL_ENTITY is deselected.
     * The legal entity (company, research institute, etc.) on whose behalf the survey is performed
     *
     * Generated from protobuf field <code>string legal_entity = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLegalEntity($var)
    {
        GPBUtil::checkString($var, True);
        $this->legal_entity = $var;

        return $this;
    }

    /**
     * Required unless SubFlow.POSTAL_ADDRESS is deselected.
     * The postal address to which callees can direct any requests.
     *
     * Generated from protobuf field <code>string postal_address = 2;</code>
     * @return string
     */
    public function getPostalAddress()
    {
        return $this->postal_address;
    }

    /**
     * Required unless SubFlow.POSTAL_ADDRESS is deselected.
     * The postal address to which callees can direct any requests.
     *
     * Generated from protobuf field <code>string postal_address = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPostalAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->postal_address = $var;

        return $this;
    }

    /**
     * Required unless SubFlow.EMAIL_ADDRESS is deselected.
     * The email address to which callees can direct any requests.
     *
     * Generated from protobuf field <code>string email_address = 3;</code>
     * @return string
     */
    public function getEmailAddress()
    {
        return $this->email_address;
    }

    /**
     * Required unless SubFlow.EMAIL_ADDRESS is deselected.
     * The email address to which callees can direct any requests.
     *
     * Generated from protobuf field <code>string email_address = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEmailAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->email_address = $var;

        return $this;
    }

    /**
     * Required unless SubFlow.PHONE_NUMBER is deselected.
     * The phone number to which callees can direct any requests.
     *
     * Generated from protobuf field <code>string phone_number = 4;</code>
     * @return string
     */
    public function getPhoneNumber()
    {
        return $this->phone_number;
    }

    /**
     * Required unless SubFlow.PHONE_NUMBER is deselected.
     * The phone number to which callees can direct any requests.
     *
     * Generated from protobuf field <code>string phone_number = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPhoneNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone_number = $var;

        return $this;
    }

    /**
     * Required unless SubFlow.PHONE_HOURS is deselected.
     * The phone hours during which callees can call (in pronounceable form).
     *
     * Generated from protobuf field <code>string phone_hours = 5;</code>
     * @return string
     */
    public function getPhoneHours()
    {
        return $this->phone_hours;
    }

    /**
     * Required unless SubFlow.PHONE_HOURS is deselected.
     * The phone hours during which callees can call (in pronounceable form).
     *
     * Generated from protobuf field <code>string phone_hours = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPhoneHours($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone_hours = $var;

        return $this;
    }

    /**
     * Required unless SubFlow.EXPECTED_DURATION is deselected.
     * The expected duration of the survey (in pronounceable form)
     *
     * Generated from protobuf field <code>string expected_duration = 6;</code>
     * @return string
     */
    public function getExpectedDuration()
    {
        return $this->expected_duration;
    }

    /**
     * Required unless SubFlow.EXPECTED_DURATION is deselected.
     * The expected duration of the survey (in pronounceable form)
     *
     * Generated from protobuf field <code>string expected_duration = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setExpectedDuration($var)
    {
        GPBUtil::checkString($var, True);
        $this->expected_duration = $var;

        return $this;
    }

    /**
     * Required unless SubFlow.PURPOSE is deselected.
     * An explanation regarding the purpose of the survey (in pronounceable form)
     *
     * Generated from protobuf field <code>string purpose = 7;</code>
     * @return string
     */
    public function getPurpose()
    {
        return $this->purpose;
    }

    /**
     * Required unless SubFlow.PURPOSE is deselected.
     * An explanation regarding the purpose of the survey (in pronounceable form)
     *
     * Generated from protobuf field <code>string purpose = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setPurpose($var)
    {
        GPBUtil::checkString($var, True);
        $this->purpose = $var;

        return $this;
    }

    /**
     * Required.
     * A one-word explanation of the survey topic (in pronounceable form)
     *
     * Generated from protobuf field <code>string topic = 8;</code>
     * @return string
     */
    public function getTopic()
    {
        return $this->topic;
    }

    /**
     * Required.
     * A one-word explanation of the survey topic (in pronounceable form)
     *
     * Generated from protobuf field <code>string topic = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setTopic($var)
    {
        GPBUtil::checkString($var, True);
        $this->topic = $var;

        return $this;
    }

    /**
     * Required.
     * A pronounceable explanation of the legal implications of participating in the survey.
     * For example:
     *  "Your answers during this survey will be stored anonymously for the next two years and then deleted."
     * Should be formulated such that the agent can afterwards ask for the consent of the user.
     * Example for how the agent could continue: "Are you willing to participate in this survey?"
     *
     * Generated from protobuf field <code>string legal_disclaimer = 9;</code>
     * @return string
     */
    public function getLegalDisclaimer()
    {
        return $this->legal_disclaimer;
    }

    /**
     * Required.
     * A pronounceable explanation of the legal implications of participating in the survey.
     * For example:
     *  "Your answers during this survey will be stored anonymously for the next two years and then deleted."
     * Should be formulated such that the agent can afterwards ask for the consent of the user.
     * Example for how the agent could continue: "Are you willing to participate in this survey?"
     *
     * Generated from protobuf field <code>string legal_disclaimer = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setLegalDisclaimer($var)
    {
        GPBUtil::checkString($var, True);
        $this->legal_disclaimer = $var;

        return $this;
    }

    /**
     * Optional.
     * Defaults to False. Allows the definition of a survey as anonymous or not.
     * If the survey is not anonymous, the name of the people as well as their number will be recorded
     *
     * Generated from protobuf field <code>bool anonymous = 10;</code>
     * @return bool
     */
    public function getAnonymous()
    {
        return $this->anonymous;
    }

    /**
     * Optional.
     * Defaults to False. Allows the definition of a survey as anonymous or not.
     * If the survey is not anonymous, the name of the people as well as their number will be recorded
     *
     * Generated from protobuf field <code>bool anonymous = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setAnonymous($var)
    {
        GPBUtil::checkBool($var);
        $this->anonymous = $var;

        return $this;
    }

}

