<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/survey/survey.proto

namespace Ondewo\Survey;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>ondewo.survey.UpdateSurveyRequest</code>
 */
class UpdateSurveyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Updated survey. Note: the ID must refer to an existing survey which will be updated
     *
     * Generated from protobuf field <code>.ondewo.survey.Survey survey = 1;</code>
     */
    protected $survey = null;
    /**
     * Optional. Field mask that defines which fields get updated. Default: all fields are updated.
     * Example:
     *          - update_mask = FieldMask( [ 'survey.display_name', 'survey.questions' ] )
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 2;</code>
     */
    protected $update_mask = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ondewo\Survey\Survey $survey
     *           Updated survey. Note: the ID must refer to an existing survey which will be updated
     *     @type \Google\Protobuf\FieldMask $update_mask
     *           Optional. Field mask that defines which fields get updated. Default: all fields are updated.
     *           Example:
     *                    - update_mask = FieldMask( [ 'survey.display_name', 'survey.questions' ] )
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Survey\Survey::initOnce();
        parent::__construct($data);
    }

    /**
     * Updated survey. Note: the ID must refer to an existing survey which will be updated
     *
     * Generated from protobuf field <code>.ondewo.survey.Survey survey = 1;</code>
     * @return \Ondewo\Survey\Survey|null
     */
    public function getSurvey()
    {
        return $this->survey;
    }

    public function hasSurvey()
    {
        return isset($this->survey);
    }

    public function clearSurvey()
    {
        unset($this->survey);
    }

    /**
     * Updated survey. Note: the ID must refer to an existing survey which will be updated
     *
     * Generated from protobuf field <code>.ondewo.survey.Survey survey = 1;</code>
     * @param \Ondewo\Survey\Survey $var
     * @return $this
     */
    public function setSurvey($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Survey\Survey::class);
        $this->survey = $var;

        return $this;
    }

    /**
     * Optional. Field mask that defines which fields get updated. Default: all fields are updated.
     * Example:
     *          - update_mask = FieldMask( [ 'survey.display_name', 'survey.questions' ] )
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 2;</code>
     * @return \Google\Protobuf\FieldMask|null
     */
    public function getUpdateMask()
    {
        return $this->update_mask;
    }

    public function hasUpdateMask()
    {
        return isset($this->update_mask);
    }

    public function clearUpdateMask()
    {
        unset($this->update_mask);
    }

    /**
     * Optional. Field mask that defines which fields get updated. Default: all fields are updated.
     * Example:
     *          - update_mask = FieldMask( [ 'survey.display_name', 'survey.questions' ] )
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 2;</code>
     * @param \Google\Protobuf\FieldMask $var
     * @return $this
     */
    public function setUpdateMask($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\FieldMask::class);
        $this->update_mask = $var;

        return $this;
    }

}

